<Project Sdk="Dalamud.NET.Sdk/13.0.0">
    <PropertyGroup>
        <PackageProjectUrl>https://github.com/cycleapple/SortaKinda/tree/api13-tw</PackageProjectUrl>
        <Version>2.1.1.6</Version>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\KamiLib\KamiLib.csproj" />
        <ProjectReference Include="..\KamiToolKit\KamiToolKit.csproj" />
    </ItemGroup>
</Project>
